Models/BikeStation.cs
using System;
using Newtonsoft.Json;

namespace bikeMvc.Models
{
    public class BikeStation
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("id")] 
        public int Id { get; set; }

        [JsonProperty("bike_count")]
        public int BikeCount { get; set; }

        [JsonProperty("slot_count")]
        public int SlotCount { get; set; }

        [JsonProperty("latitude")]
        public string Latitude { get; set; }

        [JsonProperty("longitude")]
        public string Longitude { get; set; }

        [JsonProperty("is_online")]
        public bool IsAvailable { get; set; }
    }
}

Models/BikeStationModel.cs
using System;
using System.Collections.Generic;
using System.Net;
using System.Net.Http;
using Newtonsoft.Json;

namespace bikeMvc.Models
{
    public class BikeStationModel
    {
        public List<BikeStation> StationList { get; set; }

        public BikeStationModel()
        {
            using (var client = new HttpClient()){
                var response = client.GetAsync("http://api.alexandredubois.com/vcub-backend/vcub.php");
                var stringResult = response.Result.Content.ReadAsStringAsync();
                StationList = JsonConvert.DeserializeObject<List<BikeStation>>(stringResult.Result);
            }
        }

        public BikeStation getStation(int id){
            foreach (var station in StationList)
            {
                if(station.Id == id){
                    return station;
                }
            }
            return null;
        }

        // public BikeStationModel()
        // {
        //     using (var client = new HttpClient())
        //     {
        //         var response = client.GetAsync("http://api.alexandredubois.com/vcub-backend/vcub.php");
        //         var stringResult = response.Result.Content.ReadAsStringAsync();
        //         StationList = JsonConvert.DeserializeObject<List<BikeStation>>(stringResult.Result);
        //     }
        // }
    }
}

Models/ErrorViewModel.cs
using System;

namespace bikeMvc.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/MvcRapperContext.cs
using Microsoft.EntityFrameworkCore;

namespace bikeMvc.Models
{
    public class mvcRaperContext : DbContext
    {
        public mvcRaperContext (DbContextOptions<mvcRaperContext> options)
            : base(options)
        {
        }

        public DbSet<bikeMvc.Models.Rapper> Movie { get; set; }
    }
}

Models/Rapper.cs
using System;

namespace bikeMvc.Models
{
    public class Rapper
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string NickName { get; set; }
        public DateTime CreatedOn { get; set; } = DateTime.UtcNow;
    }
}

Models/SIgnalerModel.cs
using System;
using Newtonsoft.Json;

namespace bikeMvc.Models
{
    public class SignalerModel
    {
        public SignalerModel(int idStation, int IdVelo, string message)
        {
            this.idStation = idStation;
            this.idVelo = IdVelo;
            this.message = message;
        }

        public int idStation { get; set; }
        public int idVelo { get; set; }
        public string message { get; set; }

    }
}

Models/SignalerBike.cs
using System;
using Newtonsoft.Json;

namespace bikeMvc.Models
{
    public class SignalerBike
    {
        public SignalerBike()
        {
            this.station = null;
            this.IdVelo = -1;
            this.commentaire = "";
            this.roueDefail = false;
            this.pedDefail = false;
            this.freinDefail = false;
            this.selleDefail = false;
        }

        public SignalerBike(BikeStation station,int IdVelo)
        {
            this.station = station;
            this.IdVelo  = IdVelo;
            this.commentaire = "";
            this.roueDefail = false;
            this.pedDefail = false;
            this.freinDefail = false;
            this.selleDefail = false;
        }
        public BikeStation station { get; set; }

        public int IdVelo { get; set; }
        public string commentaire { get; set; }
        public bool roueDefail {get; set;}
        public bool pedDefail {get; set;}
        public bool freinDefail {get; set;}
        public bool selleDefail {get; set;}

    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using bikeMvc.Models;

namespace bikeMvc.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/VcubController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using bikeMvc.Models;

namespace bikeMvc.Controllers{
    public class VcubController : Controller
    {
        [HttpGet("vcub/stations/liste")]
        public IActionResult Liste()
        {
            var model = new BikeStationModel();
            return View(model);
        }


        [HttpGet("vcub/stations/carte")]
        public IActionResult Carte()
        {
            var model = new BikeStationModel();
            return View(model);
        }

        [HttpGet("vcub/stations/{id}")]
        public IActionResult Detail(int id)
        {
            var model = new BikeStationModel();
            var station = model.getStation(id);
            return View(station);
        }

        [HttpGet("vcub/stations/{id}/signaler/{idVelo}")]
        public IActionResult Signaler(int id,int idVelo)
        {
            var model = new BikeStationModel();
            var station = model.getStation(id);
            var signalerBike = new SignalerBike(station, idVelo);
            return View(signalerBike);
        
        }

        [HttpPost("vcub/stations/{id}/signaler/{idVelo}")]
        public IActionResult Signaler(SignalerBike model)
        {   
            Console.WriteLine(model.commentaire);
            TempData["signaler"] = model.commentaire;
            return RedirectToAction("ThankYou");
        }

        [HttpGet("vcub/stations/thank-you")]
        public IActionResult ThankYou()
        {
            // SignalerBike signaler = (SignalerBike)TempData["signaler"];
            ViewBag.signalerMessage = TempData["signaler"];
            return View();
        }

    }
}

Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<h1>Home Page</h1>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - bikeMvc</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">bikeMvc</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li><a asp-area="" asp-controller="Vcub" asp-action="Liste">Liste des stations</a></li>
                    <li><a asp-area="" asp-controller="Vcub" asp-action="Carte">Carte des stations</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - bikeMvc</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Vcub/Carte.cshtml
<h1>Superbe carte</h1>


<div id="map" style="width:1200px;height:555px"></div>

<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB-jN7U4gF53B_YUVx4yuRXlZF9WM6zFlE&callback=initMap"></script>
<script>
    function initMap() {
        //console.log('test');
        var mapCenter = {lat: @Model.StationList[0].Latitude, lng: @Model.StationList[0].Longitude};
        var map = new google.maps.Map(document.getElementById('map'), {
            zoom: 8,
            center:mapCenter
        });

        @foreach (var station in Model.StationList){
            <text>
                var marker = new google.maps.Marker({
                    position: {
                        lat:@station.Latitude,
                        lng:@station.Longitude
                    },
                    map: map
                });
            </text>
        }
     

    }
</script>
<!-- <script src="https://maps.googleapis.com/maps/api/js?callback=initMap" async defer></script> -->

Views/Vcub/Detail.cshtml
<h1>Détail de la station : @Model.Name</h1>

@for(var id = 0; id < @Model.BikeCount; id++)
{
    <a class="btn btn-default" asp-controller="Vcub" asp-action="Signaler" asp-route-id="@Model.Id" asp-route-idVelo="@id">
        @id
        <img src="/images/bike.svg"/>
    </a>
}

@for(var i = 0; i < @Model.SlotCount; i++)
{
    <img src="/images/borne.svg"/>
}

Views/Vcub/Liste.cshtml
@using bikeMvc.Models
@model bikeMvc.Models.BikeStationModel
<h1>Liste des stations VCUB</h1>

<table class="table">
    <thead>
        <tr>
            <td>Id</td>
            <td>Nom</td>
            <td>Nb vélos</td>
            <td>Nb place(s)</td>
            <td>Disponibilité</td>
            <td>Détail</td>
            <td>Coordonnées GPS</td>
        </tr>
    </thead>
    <tbody>
        @foreach (var station in Model.StationList)
           {
               <tr class="@( @station.IsAvailable ? "": "alert-danger")">
                    <td>@station.Id</td>
                    <td>@station.Name</td>
                    <td>@station.BikeCount</td>
                    <td>@station.SlotCount</td>
                    <td>
                        @if (@station.IsAvailable) {
                            <span class="glyphicon glyphicon-ok"></span>
                        }
                        else {
                            <span class="glyphicon glyphicon-remove"></span>
                         }
                    </td>
                    <td>
                        <a class="btn btn-default" asp-controller="Vcub" asp-action="Detail" asp-route-id="@station.Id">Détail</a>
                    </td>
                    <td>
                        <a class="btn btn-default" target="_blank" href="https://www.google.fr/maps/?q=@station.Latitude,@station.Longitude">
                            Voir sur Gmaps
                        </a>
                    </td>
                </tr>
            }
    </tbody>
</table>

Views/Vcub/Signaler.cshtml
@model SignalerBike

<h1>
    Signaler un problème sur le vélo @Model.IdVelo de la station @Model.station.Name
</h1>


<form asp-controller="Vcub" 
      asp-action="Signaler" 
      asp-route-id="@Model.station.Id" 
      asp-route-idVelo="@Model.IdVelo" method="post">
      
  <div class="form-group">
    <label for="email">Commentaire</label>
    <input type="text" class="form-control" asp-for="commentaire">
    
  </div>
  <div class="checkbox">
    <h3>Type de panne</h3>
    <label>
        <input value="true" type="checkbox" asp-for="roueDefail" />
        Roue crevée/dégonflée
    </label>
    <label>
        <input value="true" type="checkbox" asp-for="pedDefail" />
        Pédalage défaillant
    </label>
    <label>
        <input value="true" type="checkbox" asp-for="freinDefail" />
        Freins non fonctionnels, 
    </label>
    <label>
        <input value="true" type="checkbox" asp-for="selleDefail" />
        Selle impossible à régler
    </label>
  </div>
  <a class="btn btn-default" asp-controller="Vcub" asp-action="Detail" asp-route-id="@Model.station.Id">Retour</a>
  <button type="submit" class="btn btn-primary">Signaler</button>


</form>


<!-- @using (Html.BeginForm("Signaler", "VCub", FormMethod.Post))
{
    <div class="form-group">
        <label for="email">Commentaire</label>
        <input type="text" asp-for="commentaire" class="form-control">
    </div>
 
} -->

Views/Vcub/ThankYou.cshtml
Merci pour ces informations

<br>
@ViewBag.signalerMessage